import { AccountingAccount } from "../../accounting/model/AccountingAccount";
import { City } from "../../miscellaneous/model/City";
import { Country } from "../../miscellaneous/model/Country";
import { Department } from "../../miscellaneous/model/Department";
import { IDocument } from "../../miscellaneous/model/IDocument";
import { Mail } from "../../miscellaneous/model/Mail";
import { PaymentType } from "../../miscellaneous/model/PaymentType";
import { Phone } from "../../miscellaneous/model/Phone";
import { SpecialOffer } from "../../miscellaneous/model/SpecialOffer";
import { VatCollectionType } from "../../miscellaneous/model/VatCollectionType";
import { WeekDay } from "../../miscellaneous/model/WeekDay";
import { JournalType } from "./JournalType";
import { Regie } from "./Regie";

export interface Confrere extends IDocument {
  id: number;
  label: string;
  code: string;
  mails: Mail[];
  accountingMails: Mail[];
  phones: Phone[];
  accountingAccountCustomer: AccountingAccount;
  accountingAccountProvider: AccountingAccount;
  accountingAccountDeposit: AccountingAccount;
  mailRecipient: string;
  address: string;
  city: City;
  postalCode: string;
  country: Country;
  iban: string;
  paymentType: PaymentType;
  paymentBIC: string;
  isSepaMandateReceived: boolean;
  isProvisionalPaymentMandatory: boolean;
  journalType: JournalType;
  reinvoicing: number;
  weekDays: WeekDay[];
  specialOffers: SpecialOffer[];
  departments: Department[];
  lastShipmentForPublication: string;
  publicationCertificateDocumentGrade: string;
  billingGrade: string;
  paperGrade: string;
  boardGrade: string;
  shippingCosts: number;
  administrativeFees: number;
  numberOfPrint: number;
  paperPrice: number;
  regie: Regie;
  observations: string;
  vatCollectionType: VatCollectionType;
}
