import { City } from "../../miscellaneous/model/City";
import { Country } from "../../miscellaneous/model/Country";
import { Department } from "../../miscellaneous/model/Department";
import { IDocument } from "../../miscellaneous/model/IDocument";
import { Mail } from "../../miscellaneous/model/Mail";
import { Phone } from "../../miscellaneous/model/Phone";
import { Provider } from "../../miscellaneous/model/Provider";
import { WeekDay } from "../../miscellaneous/model/WeekDay";
import { Responsable } from "../../tiers/model/Responsable";
import { JournalType } from "./JournalType";

export interface Confrere extends IDocument {
  label: string;
  code: string;
  departments: Department[];
  mails: Mail[];
  phones: Phone[];
  reinvoicing: number;
  weekDays: WeekDay[];
  journalType: JournalType;
  lastShipmentForPublication: string;
  publicationCertificateDocumentGrade: string;
  billingGrade: string;
  paperGrade: string;
  boardGrade: string;
  shippingCosts: number;
  discountRate: number;
  administrativeFees: number;
  numberOfPrint: number;
  paperPrice: number;
  mailRecipient: string | null;
  address: string;
  postalCode: string;
  cedexComplement: string;
  city: City;
  country: Country;
  observations: string;
  provider: Provider;
  responsable: Responsable;
}
