import { AccountingRecord } from "../../accounting/model/AccountingRecord";
import { Appoint } from "../../invoicing/model/Appoint";
import { Deposit } from "../../invoicing/model/Deposit";
import { InvoiceStatus } from "../../invoicing/model/InvoiceStatus";
import { Payment } from "../../invoicing/model/Payment";
import { City } from "../../miscellaneous/model/City";
import { CompetentAuthority } from '../../miscellaneous/model/CompetentAuthority';
import { Country } from "../../miscellaneous/model/Country";
import { IAttachment } from '../../miscellaneous/model/IAttachment';
import { PaymentType } from '../../miscellaneous/model/PaymentType';
import { Provider } from '../../miscellaneous/model/Provider';
import { TiersFollowup } from "../../miscellaneous/model/TiersFollowup";
import { BillingLabelType } from "../../tiers/model/BillingLabelType";
import { Responsable } from "../../tiers/model/Responsable";
import { Tiers } from "../../tiers/model/Tiers";
import { Confrere } from "./Confrere";
import { CustomerOrder } from "./CustomerOrder";
import { InvoiceItem } from "./InvoiceItem";

export interface Invoice extends IAttachment {
  id: number;
  createdDate: Date;
  dueDate: Date;
  invoiceItems: InvoiceItem[];
  billingLabel: string;
  billingLabelAddress: string;
  billingLabelPostalCode: string;
  billingLabelIntercommunityVat: string;
  cedexComplement: string;
  billingLabelCity: City;
  billingLabelCountry: Country;
  billingLabelIsIndividual: boolean;
  billingLabelType: BillingLabelType;
  isResponsableOnBilling: boolean;
  isCommandNumberMandatory: boolean;
  isInvoiceFromProvider: boolean;
  commandNumber: string;
  customerOrder: CustomerOrder;
  totalPrice: number;
  payments: Payment[];
  deposits: Deposit[];
  invoiceStatus: InvoiceStatus;
  accountingRecords: AccountingRecord[];
  tiers: Tiers | undefined;
  responsable: Responsable | undefined;
  confrere: Confrere | undefined;
  provider: Provider | undefined;
  competentAuthority: CompetentAuthority | undefined;
  manualPaymentType: PaymentType;
  manualAccountingDocumentDate: Date;
  manualAccountingDocumentNumber: string;
  firstReminderDateTime: Date;
  secondReminderDateTime: Date;
  thirdReminderDateTime: Date;
  tiersFollowups: TiersFollowup[];
  customerOrderForInboundInvoice: CustomerOrder;
  isCreditNote: boolean;
  isProviderCreditNote: boolean;
  creditNote: Invoice;
  reverseCreditNote: Invoice;
  appoints: Appoint[];
}
