import { IAttachment } from "../../miscellaneous/model/IAttachment";
import { Employee } from "../../profile/model/Employee";
import { Announcement } from "./Announcement";
import { AssoAffaireOrder } from "./AssoAffaireOrder";
import { Bodacc } from "./Bodacc";
import { Debour } from './Debour';
import { Domiciliation } from "./Domiciliation";
import { Formalite } from './Formalite';
import { InvoiceItem } from "./InvoiceItem";
import { ProvisionFamilyType } from "./ProvisionFamilyType";
import { ProvisionType } from "./ProvisionType";
import { SimpleProvision } from './SimpleProvision';

export interface Provision extends IAttachment {
  id: number;
  domiciliation: Domiciliation | undefined;
  announcement: Announcement | undefined;
  bodacc: Bodacc | undefined;
  simpleProvision: SimpleProvision | undefined;
  formalite: Formalite | undefined;
  provisionFamilyType: ProvisionFamilyType;
  provisionType: ProvisionType;
  invoiceItems: InvoiceItem[]
  debours: Debour[]
  assoAffaireOrder: AssoAffaireOrder;
  assignedTo: Employee;
  isLogo: boolean;
  isRedactedByJss: boolean;
  isBaloPackage: boolean; 
  isBaloPublicationFlag: boolean; 
  isBaloNormalization: boolean;
  isPublicationReceipt: boolean;
  isPublicationPaper: boolean;
  publicationPaperAffaireNumber: number;
  publicationPaperClientNumber: number;
  isPublicationFlag: boolean;
  isBodaccFollowup: boolean;
  isBodaccFollowupAndRedaction: boolean;
  isNantissementDeposit: boolean;
  isSocialShareNantissementRedaction: boolean;
  isBusinnessNantissementRedaction: boolean;
  isSellerPrivilegeRedaction: boolean;
  isTreatmentMultipleModiciation: boolean;
  isVacationMultipleModification: boolean;
  isRegisterPurchase: boolean;
  isRegisterInitials: boolean;
  isRegisterShippingCosts: boolean;
  isDisbursement: boolean;
  isFeasibilityStudy: boolean;
  isChronopostFees: boolean;
  isApplicationFees: boolean;
  isBankCheque: boolean;
  isComplexeFile: boolean;
  isBilan: boolean;
  isDocumentScanning: boolean;
  isEmergency: boolean;
  isVacationDepositBeneficialOwners: boolean;
  isVacationUpdateBeneficialOwners: boolean;
  isFormalityAdditionalDeclaration: boolean;
  isCorrespondenceFees: boolean;
}
