import { Payment } from "../../invoicing/model/Payment";
import { IAttachment } from "../../miscellaneous/model/IAttachment";
import { Employee } from "../../profile/model/Employee";
import { Announcement } from "./Announcement";
import { CustomerOrderComment } from "./CustomerOrderComment";
import { Domiciliation } from "./Domiciliation";
import { Formalite } from './Formalite';
import { Invoice } from "./Invoice";
import { InvoiceItem } from "./InvoiceItem";
import { ProvisionFamilyType } from "./ProvisionFamilyType";
import { ProvisionType } from "./ProvisionType";
import { Service } from "./Service";
import { SimpleProvision } from './SimpleProvision';

export interface Provision extends IAttachment {
  id: number;
  domiciliation: Domiciliation | undefined;
  announcement: Announcement | undefined;
  simpleProvision: SimpleProvision | undefined;
  formalite: Formalite | undefined;
  provisionFamilyType: ProvisionFamilyType;
  provisionType: ProvisionType;
  invoiceItems: InvoiceItem[]
  service: Service;
  assignedTo: Employee;
  isLogo: boolean;
  isRedactedByJss: boolean;
  isBaloPackage: boolean;
  isBaloPublicationFlag: boolean;
  isBaloNormalization: boolean;
  isPublicationReceipt: boolean;
  isPublicationPaper: boolean;
  publicationPaperAffaireNumber: number;
  publicationPaperClientNumber: number;
  isPublicationFlag: boolean;
  isBodaccFollowup: boolean;
  isBodaccFollowupAndRedaction: boolean;
  isNantissementDeposit: boolean;
  isSocialShareNantissementRedaction: boolean;
  isBusinnessNantissementRedaction: boolean;
  isSellerPrivilegeRedaction: boolean;
  isTreatmentMultipleModiciation: boolean;
  isVacationMultipleModification: boolean;
  isRegisterPurchase: boolean;
  isRegisterInitials: boolean;
  isRegisterShippingCosts: boolean;
  isDisbursement: boolean;
  isFeasibilityStudy: boolean;
  isChronopostFees: boolean;
  isApplicationFees: boolean;
  isBankCheque: boolean;
  isComplexeFile: boolean;
  isBilan: boolean;
  isDocumentScanning: boolean;
  isEmergency: boolean;
  isRneUpdate: boolean;
  isVacationUpdateBeneficialOwners: boolean;
  isFormalityAdditionalDeclaration: boolean;
  isCorrespondenceFees: boolean;
  isSupplyFullBeCopy: boolean;
  providerInvoices: Invoice[];
  payments: Payment[];
  lastCompetentAuthorityReminderDateTime: Date;
  customerOrderComments: CustomerOrderComment[];
}
