
//KPI CRM
export const OPPORTUNITY_CLOSING_AVERAGE_TIME = "OPPORTUNITY_CLOSING_AVERAGE_TIME";
export const ORDER_COMPLETION_AVERAGE_TIME = "ORDER_COMPLETION_AVERAGE_TIME";
export const PAYING_INVOICE_AVERAGE_TIME = "PAYING_INVOICE_AVERAGE_TIME";
export const MEASURED_REVENUE_CUMUL = "MEASURED_REVENUE_CUMUL";
export const OVERDUE_BALANCE = "OVERDUE_BALANCE";
export const POTENTIAL_REVENUE_CUMUL = "POTENTIAL_REVENUE_CUMUL";

export const AGGREGATE_TYPE_AVERAGE = "AGGREGATE_TYPE_AVERAGE";
export const AGGREGATE_TYPE_CUMUL = "AGGREGATE_TYPE_CUMUL";
export const AGGREGATE_TYPE_HISTORIC = "AGGREGATE_TYPE_HISTORIC";
export const AGGREGATE_TYPE_DURATION = "AGGREGATE_TYPE_DURATION";
