
//KPI CRM
export const OPPORTUNITY_CLOSING_AVERAGE_TIME = "OPPORTUNITY_CLOSING_AVERAGE_TIME";
export const ORDER_COMPLETION_AVERAGE_TIME = "ORDER_COMPLETION_AVERAGE_TIME";
export const PAYING_INVOICE_AVERAGE_TIME = "PAYING_INVOICE_AVERAGE_TIME";
export const MEASURED_REVENUE_CUMUL = "MEASURED_REVENUE_CUMUL";
export const OVERDUE_BALANCE = "OVERDUE_BALANCE";
export const POTENTIAL_REVENUE_CUMUL = "POTENTIAL_REVENUE_CUMUL";

export const AGGREGATE_TYPE_AVERAGE = "AGGREGATE_TYPE_AVERAGE";
export const AGGREGATE_TYPE_CUMUL = "AGGREGATE_TYPE_CUMUL";
export const AGGREGATE_TYPE_HISTORIC = "AGGREGATE_TYPE_HISTORIC";
export const AGGREGATE_TYPE_DURATION = "AGGREGATE_TYPE_DURATION";

export const LABEL_TYPE_NUMERIC = "numeric";
export const LABEL_TYPE_DATETIME = "datetime";
export const LABEL_TYPE_CATEGORY = "category";

export const WEEKLY_PERIOD = "WEEKLY_PERIOD";
export const MONTHLY_PERIOD = "MONTHLY_PERIOD";
export const ANNUALLY_PERIOD = "ANNUALLY_PERIOD";

export const TIERS_HOME_DISPLAY = "TIERS_HOME_DISPLAY";
export const TIERS_MAIN_DISPLAY = "TIERS_MAIN_DISPLAY";
export const TIERS_BUSINESS_DISPLAY = "TIERS_BUSINESS_DISPLAY";
export const TIERS_CUSTOMER_DISPLAY = "TIERS_CUSTOMER_DISPLAY";

export const GRAPH_TYPE_LINE = "line";
export const GRAPH_TYPE_AREA = "area";
export const GRAPH_TYPE_BAR = "bar";
export const GRAPH_TYPE_PIE = "pie";
export const GRAPH_TYPE_BOXPLOT = "boxplot";
export const GRAPH_TYPE_TREEMAP = "treemap";
export const GRAPH_TYPE_SANKEY = "sankey";
export const GRAPH_TYPE_TABLE = "table";
