import { EntityType } from "../modules/miscellaneous/model/EntityType";

// Quotation status
export const QUOTATION_STATUS_OPEN = "DRAFT";
export const QUOTATION_STATUS_ABANDONED = "ABANDONED";
export const QUOTATION_STATUS_QUOTATION_WAITING_CONFRERE = "QUOTATION_WAITING_CONFRERE";
export const QUOTATION_STATUS_TO_VERIFY = "TO_VERIFY";
export const QUOTATION_STATUS_REFUSED_BY_CUSTOMER = "REFUSED_BY_CUSTOMER";
export const QUOTATION_STATUS_SENT_TO_CUSTOMER = "SENT_TO_CUSTOMER";
export const QUOTATION_STATUS_VALIDATED_BY_CUSTOMER = "VALIDATED_BY_CUSTOMER";
export const QUOTATION_STATUS_REQUIRE_ATTENTION = "QUOTATION_STATUS_REQUIRE_ATTENTION";

export const QUOTATION_WITH_UNREAD_COMMENTS = "QUOTATION_WITH_UNREAD_COMMENTS";

// Customer order status
export const CUSTOMER_ORDER_STATUS_OPEN = "DRAFT";
export const CUSTOMER_ORDER_STATUS_ABANDONED = "ABANDONED";
export const CUSTOMER_ORDER_STATUS_WAITING_DEPOSIT = "WAITING_DEPOSIT";
export const CUSTOMER_ORDER_STATUS_TO_BILLED = "TO_BILLED";
export const CUSTOMER_ORDER_STATUS_BEING_PROCESSED = "BEING_PROCESSED";
export const CUSTOMER_ORDER_STATUS_BILLED = "BILLED";
export const CUSTOMER_ORDER_STATUS_PAYED = "PAYED";
export const CUSTOMER_ORDER_STATUS_REQUIRE_ATTENTION = "CUSTOMER_ORDER_STATUS_REQUIRE_ATTENTION";

export const CUSTOMER_ORDER_WITH_UNREAD_COMMENTS = "CUSTOMER_ORDER_WITH_UNREAD_COMMENTS";

// Service field types
export const SERVICE_FIELD_TYPE_INTEGER = "SERVICE_FIELD_TYPE_INTEGER";
export const SERVICE_FIELD_TYPE_TEXT = "SERVICE_FIELD_TYPE_TEXT";
export const SERVICE_FIELD_TYPE_TEXTAREA = "SERVICE_FIELD_TYPE_TEXTAREA";
export const SERVICE_FIELD_TYPE_DATE = "SERVICE_FIELD_TYPE_DATE";
export const SERVICE_FIELD_TYPE_SELECT = "SERVICE_FIELD_TYPE_SELECT";

export const MAX_SIZE_UPLOAD_FILES = 10485760;
export const INVOICING_PAYMENT_LIMIT_REFUND_EUROS: number = 2;
export const ASSO_SERVICE_DOCUMENT_ENTITY_TYPE: EntityType = { entityType: 'AssoServiceDocument', tabName: 'Documents du service', entryPoint: 'quotation/service' };
export const APPLICATION_CV_ENTITY_TYPE: EntityType = { entityType: 'Candidacy', tabName: 'Candidature CV', entryPoint: 'application/cv' };

export const JSS_IBAN = "FR76 3000 4007 9900 0257 1438 960"
export const JSS_BIC = "BNPAFRPPXXX"

// Screen types
export const PROVISION_SCREEN_TYPE_DOMICILIATION = "DOMICILIATION";
export const PROVISION_SCREEN_TYPE_ANNOUNCEMENT = "ANNOUNCEMENT";
export const PROVISION_SCREEN_TYPE_FORMALITE = "FORMALITE";
export const PROVISION_SCREEN_TYPE_STANDARD = "STANDARD";

export const PROVISION_ENTITY_TYPE: EntityType = { entityType: 'Provision', tabName: 'Prestation', entryPoint: 'provision/null' };

export const COOKIE_KEY = "consent-cookie";

export const COMMENT_POST_REFRESH_INTERVAL: number = 2000;
