// Quotation status
export const QUOTATION_STATUS_OPEN = "OPEN";
export const QUOTATION_STATUS_ABANDONED = "ABANDONED";
export const QUOTATION_STATUS_QUOTATION_WAITING_CONFRERE = "QUOTATION_WAITING_CONFRERE";
export const QUOTATION_STATUS_TO_VERIFY = "TO_VERIFY";
export const QUOTATION_STATUS_REFUSED_BY_CUSTOMER = "REFUSED_BY_CUSTOMER";
export const QUOTATION_STATUS_SENT_TO_CUSTOMER = "SENT_TO_CUSTOMER";
export const QUOTATION_STATUS_VALIDATED_BY_CUSTOMER = "VALIDATED_BY_CUSTOMER";

// Customer order status
export const CUSTOMER_ORDER_STATUS_OPEN = "OPEN";
export const CUSTOMER_ORDER_STATUS_ABANDONED = "ABANDONED";
export const CUSTOMER_ORDER_STATUS_WAITING_DEPOSIT = "WAITING_DEPOSIT";
export const CUSTOMER_ORDER_STATUS_TO_BILLED = "TO_BILLED";
export const CUSTOMER_ORDER_STATUS_BEING_PROCESSED = "BEING_PROCESSED";
export const CUSTOMER_ORDER_STATUS_BILLED = "BILLED";
export const CUSTOMER_ORDER_STATUS_PAYED = "PAYED";
