import { COMMA, ENTER } from "@angular/cdk/keycodes";

export const SEPARATOR_KEY_CODES: number[] = [ENTER, COMMA];
export const PROSPECT_TYPE_CODE = 'PROSPECT';
export const SEARCH_KEY_CODE: string = "F4";
export const PUBLICATION_TIERS_DOCUMENT_TYPE_CODE = "1";
export const CFE_TIERS_DOCUMENT_TYPE_CODE = "2";
export const KBIS_TIERS_DOCUMENT_TYPE_CODE = "3";
export const BILLING_TIERS_DOCUMENT_TYPE_CODE = "4";
export const DUNNING_TIERS_DOCUMENT_TYPE_CODE = "5";
export const REFUND_TIERS_DOCUMENT_TYPE_CODE = "6";
export const BILLING_CLOSURE_TIERS_DOCUMENT_TYPE_CODE = "7";
export const PROVISIONAL_RECEIPT_TIERS_DOCUMENT_TYPE_CODE = "8";
export const BILLING_TIERS_DOCUMENT_TYPE_OTHER_CODE = "AUTRES";
export const COUNTRY_CODE_FRANCE = 'FR';
export const PAYMENT_TYPE_PRELEVEMENT = "PRELEVEMENT";
export const REFUND_TYPE_VIREMENT = "VIREMENT";
export const MAX_SIZE_UPLOAD_FILES = 5242880;
export const SUSCRIPTION_TYPE_CODE_PERIODE_12M = "12"
