import { COMMA, ENTER } from "@angular/cdk/keycodes";

export const SEPARATOR_KEY_CODES: number[] = [ENTER, COMMA];
export const SEARCH_KEY_CODE: string = "F8";
export const NOTIFICATION_KEY_CODE: string = "F9";
export const SAVE_KEY_CODE: string = "F2";
export const NOTIFICATION_REFRESH_INTERVAL: number = 30 * 1000;
export const SUPERVISION_REFRESH_INTERVAL: number = 5 * 1000;
export const MAX_SIZE_UPLOAD_FILES = 10485760;
export const AZURE_CONFIDENT_THRESHOLD: number = 0.95;
export const INVOICING_PAYMENT_LIMIT_REFUND_EUROS: number = 2;
export const GUICHET_UNIQUE_BASE_URL = "https://guichet-unique.inpi.fr/";

// Screen types
export const PROVISION_SCREEN_TYPE_DOMICILIATION = "DOMICILIATION";
export const PROVISION_SCREEN_TYPE_ANNOUNCEMENT = "ANNOUNCEMENT";
export const PROVISION_SCREEN_TYPE_FORMALITE = "FORMALITE";
export const PROVISION_SCREEN_TYPE_STANDARD = "STANDARD";

// Quotation status
export const QUOTATION_STATUS_OPEN = "OPEN";
export const QUOTATION_STATUS_ABANDONED = "ABANDONED";
export const QUOTATION_STATUS_TO_VERIFY = "TO_VERIFY";
export const QUOTATION_STATUS_REFUSED_BY_CUSTOMER = "REFUSED_BY_CUSTOMER";
export const QUOTATION_STATUS_SENT_TO_CUSTOMER = "SENT_TO_CUSTOMER";
export const VALIDATED_BY_CUSTOMER = "VALIDATED_BY_CUSTOMER";

// Customer order status
export const CUSTOMER_ORDER_STATUS_OPEN = "OPEN";
export const CUSTOMER_ORDER_STATUS_ABANDONED = "ABANDONED";
export const CUSTOMER_ORDER_STATUS_WAITING_DEPOSIT = "WAITING_DEPOSIT";
export const CUSTOMER_ORDER_STATUS_TO_BILLED = "TO_BILLED";
export const CUSTOMER_ORDER_STATUS_BEING_PROCESSED = "BEING_PROCESSED";
export const CUSTOMER_ORDER_STATUS_BILLED = "BILLED";

// Announcement status
export const ANNOUNCEMENT_STATUS_IN_PROGRESS = "ANNOUNCEMENT_IN_PROGRESS";
export const ANNOUNCEMENT_STATUS_WAITING_CONFRERE = "ANNOUNCEMENT_WAITING_CONFRERE";
export const ANNOUNCEMENT_STATUS_WAITING_READ_CUSTOMER = "ANNOUNCEMENT_WAITING_READ_CUSTOMER";
export const ANNOUNCEMENT_STATUS_DONE = "ANNOUNCEMENT_DONE";
export const ANNOUNCEMENT_PUBLISHED = "ANNOUNCEMENT_PUBLISHED";

// Simple provision status
export const SIMPLE_PROVISION_STATUS_WAITING_DOCUMENT = "SIMPLE_PROVISION_WAITING_DOCUMENT";
export const SIMPLE_PROVISION_STATUS_WAITING_DOCUMENT_AUTHORITY = "SIMPLE_PROVISION_WAITING_DOCUMENT_AUTHORITY";

// Formalite provision status
export const FORMALITE_STATUS_WAITING_DOCUMENT = "FORMALITE_STATUS_WAITING_DOCUMENT";
export const FORMALITE_STATUS_WAITING_DOCUMENT_AUTHORITY = "FORMALITE_WAITING_DOCUMENT_AUTHORITY";
export const FORMALITE_AUTHORITY_REJECTED = "FORMALITE_AUTHORITY_REJECTED";
export const FORMALITE_AUTHORITY_VALIDATED = "FORMALITE_AUTHORITY_VALIDATED";

// Aggregate status
export const AGGREGATE_STATUS_NEW = "AGGREGATE_STATUS_NEW";
export const AGGREGATE_STATUS_IN_PROGRESS = "AGGREGATE_STATUS_IN_PROGRESS";
export const AGGREGATE_STATUS_WAITING = "AGGREGATE_STATUS_WAITING";
export const AGGREGATE_STATUS_DONE = "AGGREGATE_STATUS_DONE";

// Notification types
export const PERSONNAL = "PERSONNAL";

// Batch status
export const BATCH_STATUS_ACKNOWLEDGE_CODE = "ACKNOWLEDGE";
export const BATCH_STATUS_ERROR_CODE = "ERROR";

export const QUOTATION_CREATE = "QUOTATION_CREATE";
export const QUOTATION_SENT = "QUOTATION_SENT";
export const QUOTATION_REFUSED_BY_CUSOMER = "QUOTATION_REFUSED_BY_CUSOMER";
export const QUOTATION_VALIDATED_BY_CUSOMER = "QUOTATION_VALIDATED_BY_CUSOMER";
export const QUOTATION_ASSO_AFFAIRE_ORDER_VERIFY = "QUOTATION_ASSO_AFFAIRE_ORDER_VERIFY";

export const CUSTOMER_ORDER_CREATE = "CUSTOMER_ORDER_CREATE";
export const CUSTOMER_ORDER_ASSO_AFFAIRE_ORDER_VERIFY = "CUSTOMER_ORDER_ASSO_AFFAIRE_ORDER_VERIFY";
export const CUSTOMER_ORDER_BEING_PROCESSED = "CUSTOMER_ORDER_BEING_PROCESSED";
export const CUSTOMER_ORDER_BEING_PROCESSED_FROM_DEPOSIT = "CUSTOMER_ORDER_BEING_PROCESSED_FROM_DEPOSIT";
export const CUSTOMER_ORDER_ASSO_AFFAIRE_ORDER_TO_ASSIGN = "CUSTOMER_ORDER_ASSO_AFFAIRE_ORDER_TO_ASSIGN";
export const CUSTOMER_ORDER_TO_BE_BILLED = "CUSTOMER_ORDER_TO_BE_BILLED";

export const INVOICE_REMINDER_PAYMENT = "INVOICE_REMINDER_PAYMENT";

export const TIERS_DEPOSIT_MANDATORY = "TIERS_DEPOSIT_MANDATORY";

export const PROVISION_ADD_ATTACHMENT = "PROVISION_ADD_ATTACHMENT";
export const SERVICE_ADD_ATTACHMENT = "SERVICE_ADD_ATTACHMENT";
export const PROVISION_GUICHET_UNIQUE_STATUS_MODIFIED = "PROVISION_GUICHET_UNIQUE_STATUS_MODIFIED";


// Reporting datasets
export const REPORTING_DATASET_QUOTATION = "Donneur d'ordre / Devis / Prestations - année calendaire courante";
export const REPORTING_DATASET_TURNOVER_AMOUNT = "CA HT / TTC / avec et sans débours";
export const REPORTING_DATASET_TURNOVER_VAT_AMOUNT = "CA HT / TTC / avec et sans débours - TVA";
export const REPORTING_DATASET_CUSTOMER_ORDER = "Commandes";
export const REPORTING_DATASET_PROVISION = "Prestations";
export const REPORTING_DATASET_ANNOUNCEMENT = "Annonces légales";
export const REPORTING_DATASET_TIERS = "Tiers / responsables";
export const REPORTING_DATASET_PROVISION_PRODUCTION = "Production : prestations";
export const REPORTING_DATASET_RECOVERY = "Recouvrement";

// INPI Status
export const GUICHET_UNIQUE_STATUS_VALIDATION_PENDING = "VALIDATION_PENDING";
export const GUICHET_UNIQUE_STATUS_AMENDMENT_PENDING = "AMENDMENT_PENDING";
export const GUICHET_UNIQUE_STATUS_AMENDMENT_SIGNATURE_PENDING = "AMENDMENT_SIGNATURE_PENDING";
export const SERVICE_FIELD_TYPE_INTEGER = "SERVICE_FIELD_TYPE_INTEGER";
export const SERVICE_FIELD_TYPE_TEXT = "SERVICE_FIELD_TYPE_TEXT";
export const SERVICE_FIELD_TYPE_TEXTAREA = "SERVICE_FIELD_TYPE_TEXTAREA";
export const SERVICE_FIELD_TYPE_DATE = "SERVICE_FIELD_TYPE_DATE";
export const SERVICE_FIELD_TYPE_RADIO = "SERVICE_FIELD_TYPE_RADIO";

