import { COMMA, ENTER } from "@angular/cdk/keycodes";

export const SEPARATOR_KEY_CODES: number[] = [ENTER, COMMA];
export const SEARCH_KEY_CODE: string = "F8";
export const NOTIFICATION_KEY_CODE: string = "F9";
export const NOTIFICATION_REFRESH_INTERVAL: number = 30 * 1000;
export const MAX_SIZE_UPLOAD_FILES = 5242880;
export const INVOICING_PAYMENT_LIMIT_REFUND_EUROS: number = 1;

// Screen types
export const PROVISION_SCREEN_TYPE_BODACC = "BODACC";
export const PROVISION_SCREEN_TYPE_DOMICILIATION = "DOMICILIATION";
export const PROVISION_SCREEN_TYPE_ANNOUNCEMENT = "ANNOUNCEMENT";
export const PROVISION_SCREEN_TYPE_FORMALITE = "FORMALITE";
export const PROVISION_SCREEN_TYPE_STANDARD = "STANDARD";

// Quotation status
export const QUOTATION_STATUS_OPEN = "OPEN";
export const QUOTATION_STATUS_ABANDONED = "ABANDONED";
export const QUOTATION_STATUS_TO_VERIFY = "TO_VERIFY";
export const QUOTATION_STATUS_REFUSED_BY_CUSTOMER = "REFUSED_BY_CUSTOMER";
export const VALIDATED_BY_CUSTOMER = "VALIDATED_BY_CUSTOMER";

// Customer order status
export const CUSTOMER_ORDER_STATUS_OPEN = "OPEN";
export const CUSTOMER_ORDER_STATUS_ABANDONED = "ABANDONED";
export const CUSTOMER_ORDER_STATUS_WAITING_DEPOSIT = "WAITING_DEPOSIT";
export const CUSTOMER_ORDER_STATUS_TO_BILLED = "TO_BILLED";
export const CUSTOMER_ORDER_STATUS_BEING_PROCESSED = "BEING_PROCESSED";
export const CUSTOMER_ORDER_STATUS_BILLED = "BILLED";

// Announcement status
export const ANNOUNCEMENT_STATUS_NEW = "ANNOUNCEMENT_NEW";
export const ANNOUNCEMENT_STATUS_IN_PROGRESS = "ANNOUNCEMENT_IN_PROGRESS";
export const ANNOUNCEMENT_STATUS_WAITING_DOCUMENT = "ANNOUNCEMENT_WAITING_DOCUMENT";
export const ANNOUNCEMENT_STATUS_WAITING_CONFRERE = "ANNOUNCEMENT_WAITING_CONFRERE";
export const ANNOUNCEMENT_STATUS_WAITING_CONFRERE_PUBLISHED = "ANNOUNCEMENT_WAITING_CONFRERE_PUBLISHED";
export const ANNOUNCEMENT_STATUS_DONE = "ANNOUNCEMENT_DONE";
export const ANNOUNCEMENT_STATUS_WAITING_READ_CUSTOMER = "ANNOUNCEMENT_WAITING_READ_CUSTOMER";
export const ANNOUNCEMENT_STATUS_PUBLISHED = "ANNOUNCEMENT_PUBLISHED";

// Simple provision status
export const SIMPLE_PROVISION_STATUS_NEW = "SIMPLE_PROVISION_NEW";
export const SIMPLE_PROVISION_STATUS_IN_PROGRESS = "SIMPLE_PROVISION_IN_PROGRESS";
export const SIMPLE_PROVISION_STATUS_WAITING_DOCUMENT = "SIMPLE_PROVISION_WAITING_DOCUMENT";
export const SIMPLE_PROVISION_STATUS_WAITING_DOCUMENT_AUTHORITY = "SIMPLE_PROVISION_WAITING_DOCUMENT_AUTHORITY";
export const SIMPLE_PROVISION_STATUS_DONE = "SIMPLE_PROVISION_DONE";

// Bodacc status
export const BODACC_STATUS_NEW = "BODACC_NEW";
export const BODACC_STATUS_IN_PROGRESS = "BODACC_IN_PROGRESS";
export const BODACC_STATUS_WAITING_DOCUMENT = "BODACC_WAITING_DOCUMENT";
export const BODACC_STATUS_WAITING_DOCUMENT_BODACC = "BODACC_WAITING_DOCUMENT_BODACC";
export const BODACC_STATUS_WAITING_PUBLICATION = "BODACC_WAITING_PUBLICATION";
export const BODACC_STATUS_PUBLISHED = "BODACC_PUBLISHED";
export const BODACC_STATUS_DONE = "BODACC_DONE";

// Formalite status
export const FORMALITE_STATUS_NEW = "FORMALITE_NEW";
export const FORMALITE_STATUS_IN_PROGRESS = "FORMALITE_IN_PROGRESS";
export const FORMALITE_STATUS_WAITING_DOCUMENT = "FORMALITE_WAITING_DOCUMENT";
export const FORMALITE_STATUS_SENT = "FORMALITE_SENT";
export const FORMALITE_STATUS_REFUSED = "FORMALITE_REFUSED";
export const FORMALITE_STATUS_WAITING_DOCUMENT_GREFFE = "FORMALITE_WAITING_DOCUMENT_GREFFE";
export const FORMALITE_STATUS_VALIDATE = "FORMALITE_VALIDATE";
export const FORMALITE_STATUS_DONE = "FORMALITE_DONE";

// Domiciliation
export const DOMICILIATION_STATUS_NEW = "DOMICILIATION_NEW";
export const DOMICILIATION_STATUS_IN_PROGRESS = "DOMICILIATION_IN_PROGRESS";
export const DOMICILIATION_STATUS_WAITING_FOR_DOCUMENTS = "DOMICILIATION_WAITING_FOR_DOCUMENTS";
export const DOMICILIATION_STATUS_DONE = "DOMICILIATION_DONE";

// Aggregate status
export const STATUS_NEW = "NEW"; // Priorite 1
export const STATUS_IN_PROGRESS = "IN_PROGRESS"; // Priorite 2
export const STATUS_WAITING = "WAITING"; // Priorite 3
export const STATUS_WAITING_GREFFE = "WAITING_GREFFE"; // Priorite 4
export const STATUS_WAITING_AUTHORITY = "WAITING_AUTHORITY"; // Priorite 4
export const STATUS_WAITING_CONFRERE_PUBLISHED = "WAITING_CONFRERE_PUBLISHED"; // Priorite 4
export const STATUS_VALIDATE_GREFFE = "VALIDATE_GREFFE"; // Priorite 5
export const STATUS_REFUSED_GREFFE = "REFUSED_GREFFE"; // Priorite 5
export const STATUS_PUBLISHED = "PUBLISHED"; // Priorite 6
export const STATUS_DONE = "DONE"; // Priorite 7


// Notification types
export const PERSONNAL = "PERSONNAL";

export const QUOTATION_CREATE = "QUOTATION_CREATE";
export const QUOTATION_SENT = "QUOTATION_SENT";
export const QUOTATION_REFUSED_BY_CUSOMER = "QUOTATION_REFUSED_BY_CUSOMER";
export const QUOTATION_VALIDATED_BY_CUSOMER = "QUOTATION_VALIDATED_BY_CUSOMER";
export const QUOTATION_ASSO_AFFAIRE_ORDER_VERIFY = "QUOTATION_ASSO_AFFAIRE_ORDER_VERIFY";

export const CUSTOMER_ORDER_CREATE = "CUSTOMER_ORDER_CREATE";
export const CUSTOMER_ORDER_ASSO_AFFAIRE_ORDER_VERIFY = "CUSTOMER_ORDER_ASSO_AFFAIRE_ORDER_VERIFY";
export const CUSTOMER_ORDER_BEING_PROCESSED = "CUSTOMER_ORDER_BEING_PROCESSED";
export const CUSTOMER_ORDER_ASSO_AFFAIRE_ORDER_TO_ASSIGN = "CUSTOMER_ORDER_ASSO_AFFAIRE_ORDER_TO_ASSIGN";
export const CUSTOMER_ORDER_TO_BE_BILLED = "CUSTOMER_ORDER_TO_BE_BILLED";

export const INVOICE_REMINDER_PAYMENT = "INVOICE_REMINDER_PAYMENT";
