
export const Dictionnary = {

  "notice": "Texte de l'annonce",
  "affaireId": "N° de l'affaire",
  "affaireSiren": "SIREN de l'affaire",
  "affaireSiret": "SIRET de l'affaire",
  "waitedCompetentAuthorityLabel": "Autorité compétente en attente",
  "affaireLabel": "Affaire",
  "customerOrderId": "N° de la commande",
  "quotationId": "N° du devis",
  "customerOrderLabel": "Donneur d'ordre",
  "preTaxPrice": "Prix HT",
  "preTaxPriceWithoutDebour": "Prix HT (hors débours)",
  "provisionFamilyTypeLabel": "Famille de prestations",
  "provisionId": "N° prestation",
  "provisionTypeLabel": "Prestation",
  "aggregateProvisionTypeLabel": "Type de prestation",
  "taxedPrice": "Prix TTC",
  "tiersLabel": "Tiers",
  "provisionStatus": "Statut de la prestation",
  "provisionNumber": "Nombre de prestations",
  "provisionAssignedToLabel": "Responsable de la prestation",
  "publicationDateMonth": "Mois de publication",
  "salesEmployeeLabel": "Commercial",
  "customerOrderStatusLabel": "Statut de la commande",
  "quotationStatusLabel": "Statut du devis",
  "customerOrderCreatedDateMonth": "Mois de la commande",
  "customerOrderCreatedDateYear": "Année de la commande",
  "customerOrderCreatedDateWeek": "Semaine de la commande",
  "customerOrderCreatedDateDay": "Jour de la commande",
  "announcementCreatedDateMonth": "Mois de l'annonce",
  "announcementCreatedDateYear": "Année de l'annonce",
  "announcementCreatedDateWeek": "Semaine de l'annonce",
  "announcementCreatedDateDay": "Jour de l'annonce",
  "announcementStatus": "Status de l'annonce",
  "customerOrderAssignedEmployee": "Responsable de la commande",
  "quotationCreatedDateMonth": "Mois du devis",
  "quotationCreatedDateDay": "Jour du devis",
  "invoiceDateYear": "Année de la facture",
  "invoiceDateMonth": "Mois de la facture",
  "invoiceDateWeek": "Semaine de la facture",
  "invoiceDateDay": "Jour de la facture",
  "invoiceCreator": "Créateur de la facture",
  "quotationCreator": "Créateur du devis",
  "characterNumber": "Nombre de caractères",
  "publicationDateWeek": "Semaine de publication",
  "confrereAnnouncementLabel": "Confrère de l'annonce",
  "confrereLabel": "Confrère",
  "noticeTypeFamilyLabel": "Rubrique de l'annonce",
  "noticeTypeLabel": "Sous-rubrique de l'annonce",
  "month": "Mois",
  "vatAmount": "Montant de la TVA",
  "turnoverAmountWithTax": "Montant du CA",
  "turnoverAmountWithoutTax": "Montant du CA HT",
  "turnoverAmountWithoutDebourWithoutTax": "Montant du CA (hors débours, HT)",
  "turnoverAmountWithoutDebourWithTax": "Montant du CA (hors débours)",
  "vatLabel": "Libellé de TVA",
  "vatCode": "Type de TVA",
  "invoiceStatusLabel": "Statut de la facture",
  "customerOrderOriginLabel": "Origine de la commande/devis",
  "invoiceId": "Numéro de facture",
  "responsableMail": "Mail du responsable",
  "tiersMail": "Mail du tiers",
  "responsablePhone": "Téléphone du responsable",
  "tiersId": "N° du tiers",
  "responsableId": "N° du responsable",
  "responsableLabel": "Responsable",
  "tiersAddress": "Adresse du tiers",
  "tiersPostalCode": "Code postal du tiers",
  "tiersCedexComplement": "CEDEX du tiers",
  "tiersCity": "Ville du tiers",
  "tiersCountry": "Pays du tiers",
  "tiersIntercommunityVat": "N° de TVA du tiers",
  "tiersType": "Type du tiers",
  "tiersCategory": "Catégorie du tiers",
  "responsableCategory": "Catégorie du responsable",
  "responsableType": "Type du responsable",
  "isTiersIndividual": "Est personne physique ?",
  "nbrCustomerOrder": "Nombre de commandes",
  "nbrInvoices": "Nombre de factures",
  "nbrCreditNote": "Nombre d'avoirs",
  "nbrQuotation": "Nombre de devis",
  "nbrAnnouncement": "Nombre d'annonces légales",
  "announcementDepartment": "Département de l'annonce légale",
  "nbrFormalities": "Nombre de formalités",
  "docTiersPaperRecipient": "Destinataire papier du tiers",
  "docTiersPaperNumeric": "Destinataire numérique du tiers",
  "docTiersBilling": "Destinataire de la facture du tiers",
  "docTiersBillingLabel": "Libellé de la facture du tiers",
  "docResponsablePaperRecipient": "Destinataire papier du responsable",
  "docResponsablePaperNumeric": "Destinataire numérique du responsable",
  "docResponsableBilling": "Destinataire de la facture du responsable",
  "docResponsableBillingLabel": "Libellé de la facture du responsable",
  "tiersPaymentType": "Type de paiement du tiers",
  "tiersPaymentIban": "IBAN du tiers",
  "tiersPaymentBic": "BIC du tiers",
  "tiersIsProvisionnalPaymentMandatory": "Est à l'acompte ?",
  "lastReminderDate": "Date de dernière relance",
  "firstOrderYear": "Année de première commande",
  "firstOrderMonth": "Mois de première commande",
  "firstOrderWeek": "Semaine de première commande",
  "firstOrderDay": "Jour de première commande",
  "lastOrderYear": "Année de dernière commande",
  "lastOrderMonth": "Mois de dernière commande",
  "lastOrderWeek": "Semaine de dernière commande",
  "lastOrderDay": "Jour de dernière commande",
  "createdDateYear": "Année de création",
  "createdDateMonth": "Mois de création",
  "createdDateWeek": "Semaine de création",
  "createdDateDay": "Jour de création",
  "yearField": "Année",
  "monthField": "Mois",
  "weekField": "Semaine",
  "dayField": "Jour",
  "reminderType": "Type de relance",
  "payedPeriod": "Période de paiement",
  "lastResponsableFollowupDate": "Dernier suivi du responsable",
  "lastTiersFollowupDate": "Dernier suivi du tiers",
  "isProviderInvoice": "Est une facture fournisseur ?",
  "journalTypeLabel": "Type de journal",
  "customerOrderCreator": "Commande créée par",
  "REJETE_DEF_GRF": "Formalité rejetée définitivement",
  "REJETE_GRF": "Formalité rejetée",
  "RECU_PAR_LE_GRF": "Formalité reçue",
  "REPRISE": "Reprise en cours",
  "SAUVEGARDE": "Sauvegardée",
  "ENVOYE_AU_GRF": "Envoyée au greffe",
  "ENVOI_EN_COURS": "Envoi en cours",
  "VALIDE": "Validée",
  "thirdReminderDateTime": "Troisième date de relance",
  "PERSONNAL": "Notification personnelle",
  "PROVISION_ADD_ATTACHMENT": "Nouveau document sur une prestation",
  "SERVICE_ADD_ATTACHMENT": "Nouveau document sur un service",
  "ORDER_ADD_ATTACHMENT": "Nouveau document sur une commande",
  "PROVISION_GUICHET_UNIQUE_STATUS_VALIDATED": "Liasse GU validée",
  "PROVISION_GUICHET_UNIQUE_STATUS_REFUSED": "Liasse GU rejetée",
  "PROVISION_GUICHET_UNIQUE_STATUS_SIGNED": "Liasse GU signée",
  "INCIDENT_REPORT_ASKED": "Nouveau CRI à remplir"
};



