
export const Dictionnary = {

  "notice": "Texte de l'annonce",
  "affaireId": "N° de l'affaire",
  "affaireSiren": "SIREN de l'affaire",
  "affaireSiret": "SIRET de l'affaire",
  "waitedCompetentAuthorityLabel": "Autorité compétente en attente",
  "affaireLabel": "Affaire",
  "customerOrderId": "N° de la commande",
  "customerOrderLabel": "Donneur d'ordre",
  "preTaxPrice": "Prix HT",
  "preTaxPriceWithoutDebour": "Prix HT (hors débours)",
  "provisionFamilyTypeLabel": "Famille de prestations",
  "provisionId": "N° prestation",
  "provisionTypeLabel": "Prestation",
  "taxedPrice": "Prix TTC",
  "tiersLabel": "Tiers",
  "provisionStatus": "Statut de la prestation",
  "provisionAssignedToLabel": "Responsable de la prestation",
  "publicationDateMonth": "Mois de publication",
  "salesEmployeeLabel": "Commercial",
  "customerOrderStatusLabel": "Statut de la commande",
  "quotationStatusLabel": "Statut du devis",
  "customerOrderCreatedDateMonth": "Mois de la commande",
  "quotationCreatedDateMonth": "Mois du devis",
  "quotationCreatedDateDay": "Jour du devis",
  "invoiceDateMonth": "Mois de la facture",
  "invoiceDateDay": "Jour de la facture",
  "invoiceCreator": "Créateur de la facture",
  "quotationCreator": "Créateur du devis",
  "characterNumber": "Nombre de caractères",
  "publicationDateWeek": "Semaine de publication",
  "confrereAnnouncementLabel": "Confrère de l'annonce",
  "noticeTypeFamilyLabel": "Rubrique de l'annonce",
  "noticeTypeLabel": "Sous-rubrique de l'annonce",
  "month": "Mois",
  "vatAmount": "Montant de la TVA",
  "turnoverAmount": "Montant du CA",
  "vatLabel": "Libellé de TVA",
  "vatCode": "Type de TVA",
  "invoiceStatusLabel": "Statut de la facture",
  "customerOrderOriginLabel": "Origine de la commande/devis",
  "invoiceId": "Numéro de facture",
  "responsableMail": "Mail du responsable",
  "responsablePhone": "Téléphone du responsable"
};

