import { Voucher } from "../../crm/model/Voucher";
import { City } from "../../miscellaneous/model/City";
import { Civility } from "../../miscellaneous/model/Civility";
import { Country } from "../../miscellaneous/model/Country";
import { IAttachment } from "../../miscellaneous/model/IAttachment";
import { IDocument } from "../../miscellaneous/model/IDocument";
import { Language } from "../../miscellaneous/model/Language";
import { Mail } from "../../miscellaneous/model/Mail";
import { Phone } from "../../miscellaneous/model/Phone";
import { TiersFollowup } from "../../miscellaneous/model/TiersFollowup";
import { Employee } from "../../profile/model/Employee";
import { SubscriptionPeriodType } from "./SubscriptionPeriodType";
import { Tiers } from "./Tiers";
import { TiersCategory } from "./TiersCategory";
import { TiersType } from "./TiersType";

export interface Responsable extends IDocument, IAttachment {
  id: number;
  tiers: Tiers;
  isActive: boolean;
  isBouclette: boolean;
  function: string;
  building: string;
  floor: string;
  subscriptionPeriodType: SubscriptionPeriodType;
  tiersType: TiersType;
  tiersCategory: TiersCategory;
  civility: Civility;
  firstname: string | null;
  lastname: string | null;
  loginWeb: string;
  canViewAllTiersInWeb: boolean;
  idAs400: string;
  salesEmployee: Employee | undefined;
  defaultCustomerOrderEmployee: Employee | undefined;
  formalisteEmployee: Employee | undefined;
  insertionEmployee: Employee | undefined;
  mailRecipient: string | null;
  language: Language;
  address: string;
  postalCode: string;
  cedexComplement: string;
  city: City;
  country: Country;
  mail: Mail;
  phones: Phone[];
  tiersFollowups: TiersFollowup[];
  observations: string;
  rffIban: string;
  rffBic: string;
  rffMail: string;
  numberOfGiftPostsPerMonth: number;
  vouchers: Voucher[];
}
