import { PaymentType } from './../../miscellaneous/model/PaymentType';
import { City } from "../../miscellaneous/model/City";
import { Civility } from "../../miscellaneous/model/Civility";
import { Country } from "../../miscellaneous/model/Country";
import { DeliveryService } from "../../miscellaneous/model/DeliveryService";
import { Language } from "../../miscellaneous/model/Language";
import { Employee } from "../../profile/model/Employee";
import { Mail } from "./Mail";
import { Phone } from "./Phone";
import { SpecialOffer } from "./SpecialOffer";
import { TiersCategory } from "./TiersCategory";
import { TiersDocument } from "./TiersDocument";
import { TiersType } from "./TiersType";
import { TiersAttachment } from './TiersAttachment';

export interface Tiers {
  id: number;
  tiersType: TiersType;
  denomination: string | null;
  firstBilling: Date;
  isIndividual: boolean;
  civility: Civility | null;
  firstname: string | null;
  lastname: string | null;
  tiersCategory: TiersCategory;
  salesEmployee: Employee | null;
  formalisteEmployee: Employee | null;
  insertionEmployee: Employee | null;
  mailRecipient: string | null;
  language: Language;
  deliveryService: DeliveryService;
  address: string;
  postalCode: string;
  city: City;
  country: Country;
  intercom: string;
  intercommunityVat: string | null;
  specialOffer: SpecialOffer | null;
  rcaFormaliteRate: number;
  rcaInsertionRate: number;
  mails: Mail[];
  phones: Phone[];
  instructions: string;
  observations: string;
  documents: TiersDocument[];
  paymentType: PaymentType;
  paymentIBAN: string;
  isProvisionalPaymentMandatory: boolean;
  tiersAttachments: TiersAttachment[];
}
