import { Mail } from "../../general/model/Mail";
import { City } from "../../profile/model/City";
import { Civility } from "../../profile/model/Civility";
import { Country } from "../../profile/model/Country";
import { Phone } from "../../profile/model/Phone";
import { BuildingDomiciliation } from "./BuildingDomiciliation";
import { DomiciliationContractType } from "./DomiciliationContractType";
import { Language } from "./Language";
import { LegalForm } from "./LegalForm";
import { MailRedirectionType } from "./MailRedirectionType";


export interface Domiciliation {
  id: number;
  domiciliationContractType: DomiciliationContractType;
  language: Language;
  buildingDomiciliation: BuildingDomiciliation;
  mailRedirectionType: MailRedirectionType;
  address: string;
  postalCode: string;
  cedexComplement: string;
  city: City;
  country: Country;
  mails: Mail[];
  mailRecipient: string;
  activityDescription: string;
  activityAddress: string;
  activityPostalCode: string;
  activityCedexComplement: string;
  activityCity: City;
  activityCountry: Country;
  activityMailRecipient: string;
  activityMails: Mail[];
  accountingRecordDomiciliation: string;
  isLegalPerson: boolean;
  legalGardianCivility: Civility;
  legalGardianFirstname: string;
  legalGardianLastname: string;
  legalGardianBirthdate: Date;
  legalGardianPlaceOfBirth: string;
  legalGardianJob: string;
  legalGardianSiren: string;
  legalGardianDenomination: string;
  legalGardianLegalForm: LegalForm | undefined;
  legalGardianMailRecipient: string;
  legalGardianAddress: string;
  legalGardianPostalCode: string;
  legalGardianCedexComplement: string;
  legalGardianCity: City;
  legalGardianCountry: Country;
  legalGardianMails: Mail[];
  legalGardianPhones: Phone[];
  // domiciliationStatus: DomiciliationStatus;
  // domiciliationFees: DomiciliationFee[];
}
