import { AccountingJournal } from "../../accounting/model/AccountingJournal";
import { InvoiceStatus } from "../../invoicing/model/InvoiceStatus";
import { PaymentWay } from "../../invoicing/model/PaymentWay";
import { ActType } from "../../quotation/model/ActType";
import { AssignationType } from "../../quotation/model/AssignationType";
import { BodaccPublicationType } from "../../quotation/model/BodaccPublicationType";
import { Confrere } from "../../quotation/model/Confrere";
import { DomiciliationContractType } from "../../quotation/model/DomiciliationContractType";
import { FormeJuridique } from '../../quotation/model/guichet-unique/referentials/FormeJuridique';
import { TypeFormalite } from '../../quotation/model/guichet-unique/referentials/TypeFormalite';
import { TypePersonne } from '../../quotation/model/guichet-unique/referentials/TypePersonne';
import { JournalType } from "../../quotation/model/JournalType";
import { MailRedirectionType } from "../../quotation/model/MailRedirectionType";
import { QuotationLabelType } from "../../quotation/model/QuotationLabelType";
import { TransfertFundsType } from "../../quotation/model/TransfertFundsType";
import { BillingLabelType } from "../../tiers/model/BillingLabelType";
import { RefundType } from "../../tiers/model/RefundType";
import { SubscriptionPeriodType } from "../../tiers/model/SubscriptionPeriodType";
import { TiersType } from "../../tiers/model/TiersType";
import { AttachmentType } from "./AttachmentType";
import { BillingType } from "./BillingType";
import { CompetentAuthorityType } from "./CompetentAuthorityType";
import { Country } from "./Country";
import { Department } from "./Department";
import { DocumentType } from "./DocumentType";
import { LegalForm } from "./LegalForm";
import { PaymentType } from "./PaymentType";
import { Vat } from "./Vat";

export interface Constant {
  id: number;
  billingLabelTypeCodeAffaire: BillingLabelType;
  billingLabelTypeOther: BillingLabelType;
  billingLabelTypeCustomer: BillingLabelType;
  accountingJournalSales: AccountingJournal;
  accountingJournalPurchases: AccountingJournal;
  accountingJournalANouveau: AccountingJournal;
  tiersTypeProspect: TiersType;
  documentTypePublication: DocumentType;
  documentTypeCfe: DocumentType;
  documentTypeKbis: DocumentType;
  documentTypeBilling: DocumentType;
  documentTypeDunning: DocumentType;
  documentTypeRefund: DocumentType;
  documentTypeBillingClosure: DocumentType;
  documentTypeProvisionnalReceipt: DocumentType;
  documentTypeProofReading: DocumentType;
  documentTypePublicationCertificate: DocumentType;
  documentTypeQuotation: DocumentType;
  attachmentTypeKbis: AttachmentType;
  attachmentTypeCni: AttachmentType;
  attachmentTypeLogo: AttachmentType;
  attachmentTypeProofOfAddress: AttachmentType;
  countryFrance: Country;
  countryMonaco: Country;
  billingTypeLogo: BillingType;
  quotationLabelTypeOther: QuotationLabelType;
  paymentTypePrelevement: PaymentType;
  paymentTypeVirement: PaymentType;
  paymentTypeCB: PaymentType;
  paymentTypeEspeces: PaymentType;
  refundTypeVirement: RefundType;
  subscriptionPeriodType12M: SubscriptionPeriodType;
  legalFormUnregistered: LegalForm;
  journalTypeSpel: JournalType;
  confrereJss: Confrere;
  domiciliationContractTypeKeepMail: DomiciliationContractType;
  domiciliationContractTypeRouteEmail: DomiciliationContractType;
  domiciliationContractTypeRouteMail: DomiciliationContractType;
  domiciliationContractTypeRouteEmailAndMail: DomiciliationContractType;
  mailRedirectionTypeOther: MailRedirectionType;
  bodaccPublicationTypeMerging: BodaccPublicationType;
  bodaccPublicationTypeSplit: BodaccPublicationType;
  bodaccPublicationTypePartialSplit: BodaccPublicationType;
  bodaccPublicationTypePossessionDispatch: BodaccPublicationType;
  bodaccPublicationTypeEstateRepresentativeDesignation: BodaccPublicationType;
  bodaccPublicationTypeSaleOfBusiness: BodaccPublicationType;
  actTypeSeing: ActType;
  actTypeAuthentic: ActType;
  assignationTypeEmployee: AssignationType;
  transfertFundsTypePhysique: TransfertFundsType;
  transfertFundsTypeMoral: TransfertFundsType;
  transfertFundsTypeBail: TransfertFundsType;
  competentAuthorityTypeRcs: CompetentAuthorityType;
  competentAuthorityTypeCfp: CompetentAuthorityType;
  invoiceStatusSend: InvoiceStatus;
  invoiceStatusPayed: InvoiceStatus;
  invoiceStatusCancelled: InvoiceStatus;
  paymentWayInbound: PaymentWay;
  paymentWayOutboud: PaymentWay;
  vatTwenty: Vat;
  vatEight: Vat;
  departmentMartinique: Department;
  departmentGuadeloupe: Department;
  departmentReunion: Department;
  typePersonnePersonnePhysique: TypePersonne;
  typePersonnePersonneMorale: TypePersonne;
  typePersonneExploitation: TypePersonne;
  formeJuridiqueEntrepreneurIndividuel: FormeJuridique;
  typeFormaliteCessation: TypeFormalite;
  typeFormaliteModification: TypeFormalite;
  typeFormaliteCreation: TypeFormalite;
  typeFormaliteCorrection: TypeFormalite;
}
