import { BillingClosureRecipientType } from "../../tiers/model/BillingClosureRecipientType";
import { BillingClosureType } from "../../tiers/model/BillingClosureType";
import { BillingLabelType } from "../../tiers/model/BillingLabelType";
import { PaymentDeadlineType } from "../../tiers/model/PaymentDeadlineType";
import { RefundType } from "../../tiers/model/RefundType";
import { City } from "./City";
import { Country } from "./Country";
import { DocumentType } from "./DocumentType";
import { Mail } from "./Mail";

export interface Document {
  id: number | undefined;
  code: string;
  documentType: DocumentType;
  isRecipientClient: boolean;
  isRecipientAffaire: boolean;
  affaireAddress: string;
  clientAddress: string;
  affaireRecipient: string;
  clientRecipient: string;
  mails: Mail[];
  numberMailingAffaire: number;
  numberMailingClient: number;
  mailsClient: Mail[];
  addToClientMailList: boolean;
  mailsAffaire: Mail[];
  addToAffaireMailList: boolean;
  billingLabelType: BillingLabelType;
  isResponsableOnBilling: boolean;
  isCommandNumberMandatory: boolean;
  commandNumber: string;
  paymentDeadlineType: PaymentDeadlineType;
  refundType: RefundType;
  refundIBAN: string;
  refundBic: string;
  billingClosureType: BillingClosureType;
  billingClosureRecipientType: BillingClosureRecipientType;
  billingLabel: string;
  billingAddress: string;
  billingPostalCode: string;
  cedexComplement: string;
  billingLabelCity: City;
  billingLabelCountry: Country;
  billingLabelIsIndividual: boolean;
  externalReference: string;
}
